### ISSUE TITLE
How to Tweak an enum?

### ISSUE THREAD

**Issue by SebastianBoldt** [Khan/SwiftTweaks#112]
Is it possible to tweak an enum so it is possible to change the enums value on runtime. 
Currently i am using an int for that and remap its value to the enum at runtime but this has one major downside: Inside the Tweak-Menu there are just numbers so if have to guess which number corresponds with which enum value. 

I read something about stringOptions but there is nothing i can found in the docs that helped me with using it the right way.

**Comment by bryanjclark** [comment]
Hey Sebastian!

Yep, we use `stringOption` at Khan Academy to support that use case — and you're right, the documentation around that feature isn't great.

For example, we have a simple 3-case enum for many of our A/B tests, like so:

```
	/// Here's an example A/B test variant
	enum NewPageDesign: String  {
		case decideRandomly = "decide_randomly"
		case newDesign = "new_design"
                case oldDesign = "old_design"

                static let allCases: [NewPageDesign]= [.decideRandomly, .newDesign, .oldDesign]
	}
```

With this string-based enum, we can then create a `Tweak<StringOption>` using the underlying string-values for each case:

```
public static let newPageDesign = Tweak<StringOption>.stringList(
  "Experiments", 
  "Page Design", 
  "Use New Page Design", 
  options: NewPageDesign.allCases.map { $0.rawValue }
)
```

...and then in your code, when you want to use the tweak:
```
let myVariant: String = ExampleTweaks.assign(ExampleTweaks.newPageDesign)
let enumCase = NewPageDesign(rawValue: myVariant)!
```

We do have some more elaborate protocol code in our app for this A/B test example (for example, the protocol includes a "decider" that calculates which variant a user would see in production) but the above code outlines one method for using an enum in SwiftTweaks: map each `case` out to a `StringOption`, and then convert that `String` back into the appropriate `case`.

There may be other ways to do it, but this has been sufficient for our needs with A/B testing an enum, and our A/B testing infrastructure needed strings for each variant anyways, so that's why `StringOption` exists!
