### ISSUE TITLE
Add "force restart" configuration option to Tweak

### ISSUE THREAD

**Issue by VilemKurz** [Khan/SwiftTweaks#159]
- [x] I have read through CONTRIBUTING.md :black_heart:

**Is your feature request related to a problem? Please describe.**
Some tweaks need a restart of the app in order they become effective.

**Describe the solution you'd like**
Add `requiresRestart` optional property with default value to `false` to `Tweak`. When such tweak is tweaked, user should be presented with alert explaining that the tweak he did requires restarting of the app, with two options: `Cancel` and `Kill the app`.

**Describe alternatives you've considered**
Tried to use binding, but the closure is executed also immediately, without anyone actually tweak the value. So the app is killed on launch.

**Additional context**
This is a duplicate of older, abandoned feature request https://github.com/Khan/SwiftTweaks/issues/101.

**Comment by bryanjclark** [comment]
Thanks for the feature request! I don't anticipate implementing this, since there's generally been a lack of interest in this feature - but you might try using a binding along with, say, an `NSUserDefault` that persists the most-recent value. You could compare the two, and if there's a difference, your app could know that something changed in SwiftTweaks' UI, and you could handle that in your app's logic.
