### ISSUE TITLE
Consider changing TweaksViewController.delegate from `unowned` to `weak`

### ISSUE THREAD

**Issue by DanielAsher** [Khan/SwiftTweaks#45]
In order to integrate with [RxSwift's](https://github.com/ReactiveX/RxSwift) `DelegateProxy` mechanism, `TweaksViewController.delegate` could be changed from `unowned` to `weak`.

This [gist](https://gist.github.com/DanielAsher/71482413890ab2ac412dd5566ac22535) shows the required DelegateProxy implementation and an example call to `rx_pressedDone`.

No dependency on `RxSwift` is required of the `SwiftTweaks` project

The required change to SwiftTweaks can be seen in this [commit](https://github.com/DanielAsher/SwiftTweaks/commit/a5f29a79eae780801c9b133a0262d21123ccd0eb).

Please let me know if you would like me to submit a pull request.

**Comment by NachoSoto** [comment]
Hmm why? `unowned` is semantically more correct because we don't expect the controller to outlive the delegate. Furthermore, there would be no reasonable way to handle the case where the delegate is `nil` (and yes, I don't consider failing silently to do anything reasonable).

I'm curious how you're using the view controller that extends the live of the controller past its delegate.

**Comment by DanielAsher** [comment]
Hi @NachoSoto - thanks for the speedy response!

`unowned` is semantically more correct if the delegate is injected in the constructor and owns `TweakViewController`, however, if this is not the case (an in the example above), the DelegateProxy is not retained and causes a runtime crash `swift_unknownUnownedLoadStrong`.

To be honest, I'm not entirely sure why `weak` solves this problem - a better understanding of ARC is required. I do think that the requirement of constructor-based dependency injection of an owning delegate object is too restrictive. It disallows, for example, integration with reactive libraries delegate proxy mechanisms.

**Comment by NachoSoto** [comment]
Then that does not solve the problem, it's masking it because all the calls fail silently, which is exactly the part that I think is a very bad idea.

I don't think this disallows using any sort of proxy mechanism. I'm not as familiar with RxSwift's memory management model as I am with RAC, but either way it should be the subscription that holds a strong reference to it, not the view controller artificially extending the lifetime of its delegate.

**Comment by bryanjclark** [comment]
Heya!

At this point, I'm inclined to close this issue out, since there hasn't been a response to Nacho's comment above in awhile.

If you'd like to reopen it and discuss more, please do!

Cheers.
