### ISSUE TITLE
"Umbrella header 'SwiftTweaks.h' not found"

### ISSUE THREAD

**Issue by RafaelGadret** [Khan/SwiftTweaks#61]
HI!
Downloaded SwiftTweaks from Github
make no alterations in the project
try to build framework and get "Umbrella header 'SwiftTweaks.h' not found"
Search in Stackoverflow and it says that 
"This usually happens after a project rename or something like that. The problem is that the umbrella header is no longer listed as a Public header."
(http://stackoverflow.com/questions/30355133/swift-framework-umbrella-header-h-not-found)
but I checked and the headers SwiftTweaks.h is already on the "public" headers section
Thanks in advance for any help!

**Comment by bryanjclark** [comment]
This project has a submodule, [xcconfigs](https://github.com/jspahrsummers/xcconfigs), which helps organize our Xcode build settings for Debug, Release, etc.

When you download the zip file, that doesn't come with the `.git` repository information, so your computer has no idea that there's a git submodule, and hence Xcode is confused where these dependencies are!

To fix this, clone this repository rather than downloading the zip file, then tell git to update the submodules. For example:

`git clone git@github.com:Khan/SwiftTweaks.git`
`git submodule update`

...that'll clone the project to the current folder, and then install the required submodule. Now that the Debug.xcconfig file exists, Xcode will be able to build the example project!
