### ISSUE TITLE
Add @discardableResult to bind and bindMultiple?

### ISSUE THREAD

**Issue by runningskull** [Khan/SwiftTweaks#84]
After #73 (which is great), I'm getting warnings about the unused result of `bind` and `bindMultiple`. Can we add a `@discardableResult` to them? (relatively new to Swift & not sure if this is a good/bad practice)

Thanks!

**Comment by bryanjclark** [comment]
Those are good warnings! If you don't handle 'em properly, then there are memory leaks. 

In cases where I'm like "ugh I know I know but I really don't care about this" then I'll throw in an underscore to ignore the result:
`_ = KhanTweaks.bind(...) {`

...but I'd rather that people still see compiler warnings about potential memory leaks!

(That said - I didn't know about `@discardableResult` -- neat attribute!)

**Comment by warpling** [comment]
What's the potential memory leak? Is it that `self` captured in the bind block could lead to SwiftTweaks retaining a reference to the class when it should be dereferenced? Doesn't the same issue persist even if we keep reference to the result of `bind(…)`?

**Comment by ShivaHuang** [comment]
We had further discuss at https://github.com/Khan/SwiftTweaks/pull/121#issuecomment-451246655.

I do agree we should do our best to prevent users make mistakes. However, I think make it *undiscardable* may not achieve this goal.

The reason is, no matter you remember the `[weak self]` or not, you will see an Xcode warning saying `Result of call to 'bind(_:binding:)' is unused`, and maybe an auto fix option to insert `_ = ` before your call.
There are no warnings mentions about `[weak self]` or retain cycle.

Further more, I think this may lead users for wrong direction. Those users who not that careful may think, "Oh, Xcode reminds me I forgot to keep the result, and add `_ =` solved this warning, great!" and never thought about memory leaks.

I've searched for a while, but not found a good solution. One might help is an article here https://medium.com/anysuggestion/preventing-memory-leaks-with-swift-compile-time-safety-49b845df4dc6
It suggests

> wraps the passed delegate object as a weak reference

thus enforced we weakly hold the variable, such as `self`.
This technique is also used in Swift Foundation’s [UndoManager.registerUndo(withTarget:handler:)](https://developer.apple.com/documentation/foundation/undomanager/2427208-registerundo)

In the discussion section of Apple's documentation says,

> To avoid retain cycles with the target, operate on the closure parameter rather than on variables in an outer scope that reference the same target. For example, in the code listing above, the closure operates on the $0 parameter rather than directly on bouquetSelection.

To do this, the `bind` method would change to something like 
`static func bind<T, TargetType>(_ tweak: Tweak<T>, to target: TargetType, binding: @escaping (TargetType, T) -> Void) -> TweakBindingIdentifier where TargetType : AnyObject`

I'm not sure if this is a good design to prevent user carelessly making a retain cycle, I think it can also not solve the problem completely, any ideas?
